# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

McCOIL_categorical_cpp <- function(paramList) {
    invisible(.Call('McCOILR_McCOIL_categorical_cpp', PACKAGE = 'McCOILR', paramList))
}

McCOIL_proportional_cpp <- function(paramList) {
    invisible(.Call('McCOILR_McCOIL_proportional_cpp', PACKAGE = 'McCOILR', paramList))
}

