# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' McCOIL_categorical_cpp
#' @description
#' Categorical cpp code
#' 
#' @param paramList A list of parameters created with equivalent R function
#' 
#' @details
#' \code{McCOIL_categorical_cpp} implements THE REAL McCOIL categorical method
#' 
#' @export
McCOIL_categorical_cpp <- function(paramList) {
    invisible(.Call(`_McCOILR_McCOIL_categorical_cpp`, paramList))
}

#' @title
#' McCOIL_proportional_cpp
#' @description
#' Proportional cpp code
#' 
#' @param paramList A list of parameters created with equivalent R function
#' 
#' @details
#' \code{McCOIL_proportional_cpp} implements THE REAL McCOIL proportional method
#' 
#' @export
McCOIL_proportional_cpp <- function(paramList) {
    invisible(.Call(`_McCOILR_McCOIL_proportional_cpp`, paramList))
}

