# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' McCOIL_categorical_cpp
#' @description
#' Categorical cpp code
#' 
#' @param paramList A list of parameters created with equivalent R function
#' 
#' @details
#' \code{McCOIL_categorical_cpp} implements THE REAL McCOIL categorical method
#' 
#' @export
McCOIL_categorical_cpp <- function(paramList) {
    invisible(.Call('_McCOILR_McCOIL_categorical_cpp', PACKAGE = 'McCOILR', paramList))
}

#' @title
#' McCOIL_proportional_cpp
#' @description
#' Proportional cpp code
#' 
#' @param paramList A list of parameters created with equivalent R function
#' 
#' @details
#' \code{McCOIL_proportional_cpp} implements THE REAL McCOIL proportional method
#' 
#' @export
McCOIL_proportional_cpp <- function(paramList) {
    invisible(.Call('_McCOILR_McCOIL_proportional_cpp', PACKAGE = 'McCOILR', paramList))
}

#' @title
#' McCOIL_proportional_Rcpp
#' @description
#' Proportional cpp code that thins outputs, and stores outputs rather than 
#' writing to file. 
#' 
#' @param paramList A list of parameters created with equivalent R function
#' 
#' @details
#' \code{McCOIL_proportional_Rcpp} implements THE REAL McCOIL proportional
#'   method
#' 
#' @return Rcpp List
#' 
#' @export
McCOIL_proportional_Rcpp <- function(paramList) {
    .Call('_McCOILR_McCOIL_proportional_Rcpp', PACKAGE = 'McCOILR', paramList)
}

